name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - boost-cpp=1.87.0=h7a4561d_1
  - bzip2=1.0.8=h7223423_8
  - clang-resource-headers=20.1.8=hc286ada_0
  - cppinterop=1.7.0=h2072262_7
  - emscripten-abi=3.1.73=h267e887_12
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - nlohmann_json=3.12.0=h2072262_0
  - nlohmann_json-abi=3.12.0=h0f90c79_1
  - openblas=0.3.26=he2bab3c_14
  - pip=25.2=pyh145f28c_0
  - python=3.13.1=h_c8de616_5_cp313
  - python_abi=3.13.1=1_cp313
  - symengine=0.14.0=h07d2894_6
  - xcanvas=0.6.0=h2072262_1
  - xeus=5.2.4=h2072262_1
  - xeus-cpp=0.8.0=h2072262_0
  - xproperty=0.12.1=h2072262_0
  - xsimd=13.2.0=py313h1913ddd_1
  - xtensor=0.27.1=h2072262_0
  - xtensor-blas=0.23.0=h2072262_1
  - xtl=0.8.0=h2072262_1
  - xwidgets=0.29.1=h2072262_0
